# Generated by Django 5.0.4 on 2024-05-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='type',
            new_name='type_supplier',
        ),
    ]
